global:
 scrape_interval: 15s
scrape_configs:
 - job_name: 'prometheus_scrape_self'
   scrape_interval: 5s
   static_configs:
   - targets: ['localhost:9090']
 - job_name: 'node_exporter_scraper'
   scrape_interval: 5s
   static_configs:
   - targets: ['localhost:9100']