---
- hosts: sample-group
  remote_user: alokshrivastwa
  become: yes
  become_method: sudo
  tasks:
    - name: "Install Apache"
      apt: name={{ item }} state=present
      with_items:
        - apache2

    - name: "Turn on Apache to run on boot"
      service: name={{ item }} state=started enabled=yes
      with_items:
        - apache2